### ISSUE TITLE
Allow the use of Expression or Functions to execute problems without allocating memory for all problems at once.

### ISSUE THREAD

**Issue by MonssafToukal** [ProofOfConceptForJuliSmoothOptimizers/BBModels.jl#41]

**Comment by tmigot** [comment]
It is done with list of functions, see https://github.com/ProofOfConceptForJuliSmoothOptimizers/BBModels.jl/blob/495ad25c2389cf5eeb554a25712b93cac8afc51a/test/runtests.jl#L18
